apps/eleccion/urls.py
"""conf URL Configuration
The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
"""
from django.urls import path
from . import views

app_name = 'eleccion'
urlpatterns = [
    # _Cargo
    path('cargos/', views.CargoListView.as_view(), name='cargo-list'),
    path('cargos/active/<int:pk>', views.active_cargo, name='active_cargo'),
    path('cargos/deactive/<int:pk>', views.deactive_cargo, name='deactive_cargo'),
    path('cargos/add/', views.CargoCreateView.as_view(), name='add-cargo'),
    path('cargos/edit/<int:pk>/', views.CargoUpdateView.as_view(), name='edit-cargo'),
    # _Candidato
    path('candidatos/', views.CandidatoListView.as_view(), name='candidato-list'),
    path('candidatos/active/<int:pk>', views.active_candidato, name='active_candidato'),
    path('candidatos/deactive/<int:pk>',
         views.deactive_candidato, name='deactive_candidato'),
    path('candidatos/add/', views.CandidatoCreateView.as_view(), name='add-candidato'),
    path('candidatos/edit/<int:pk>/',
         views.CandidatoUpdateView.as_view(), name='edit-candidato'),
    # _ Eleccion
    path('', views.EleccionListView.as_view(), name='eleccion-list'),
    path('active/<int:pk>', views.active_eleccion, name='active_eleccion'),
    path('deactive/<int:pk>', views.deactive_eleccion, name='deactive_eleccion'),
    path('add/', views.EleccionCreateView.as_view(), name='add-eleccion'),
    # path('edit/<int:pk>/', views.EleccionUpdateView.as_view(), name='edit-eleccion'),
    path('edit/<slug:slug>/', views.EleccionUpdateView.as_view(), name='edit-eleccion'),
    path('<slug:slug>/', views.EleccionDetailView.as_view(), name='eleccion-detail'),
    path('<slug:slug>/add-candidato',
         views.EleccionCandidatoCreateView.as_view(), name='eleccion-candidato'),
    path('<slug:slug>/programar/',
         views.EleccionProgramar.as_view(), name='programar-eleccion'),

]

conf/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.index.urls')),
    path('accounts/', include('apps.usuarios.urls')),
    path('padron/', include('apps.padron.urls')),
    path('eleccion/', include('apps.eleccion.urls')),
    path('votacion/', include('apps.votacion.urls')),
]

apps/eleccion/models.py
import datetime

from django.db.models.signals import post_save
from django.utils.text import slugify
from django.utils import timezone
from django.urls import reverse
from django.db import models
from datetime import datetime as dt

from ..BaseModel import Base
from ..padron.models import Elector, Padron


#
# Create your models here.


ELECCION_STATUS = [(0, "Pendiente"), (1, "Programada"), (2, "En curso"),
                   (3, "Finalizada"), (4, "Suspendida"), (5, "Potergada")]


class Eleccion(Base):
    title = models.CharField(max_length=100, null=False, blank=False)
    date = models.DateField(default=datetime.date.today)
    start_time = models.TimeField(blank=True, null=True)
    end_time = models.TimeField(blank=True, null=True)
    slug = models.SlugField(max_length=50, null=False, blank=False, unique=True)
    # eleccion_estatus = models.IntegerField(choices=ELECCION_ESTATUS, default=0)
    status = models.IntegerField(choices=ELECCION_STATUS, default=0)
    # Relationships
    padron = models.ForeignKey(Padron, on_delete=models.SET_NULL, null=True)
    cargo = models.ForeignKey('Cargo', on_delete=models.SET_NULL, null=True)

    @property
    def in_process(self):
        return self.start_time <= timezone.now() and timezone.now() < self.end_time

    @property
    def not_started(self):
        return timezone.now() < self.start_time

    class Meta:
        ordering = ['date', 'title']
        verbose_name = 'Eleccion'
        verbose_name_plural = 'Elecciones'

    def get_field_values(self):
        if self.status == 0:
            return [self.title, self.cargo,
                    self.date.strftime("%d-%m-%Y"),
                    '00:00-00:00',
                    self.get_status_display()]
        else:
            return [self.title, self.cargo,
                    self.date.strftime("%d-%m-%Y"),
                    f'{self.start_time.strftime("%H:%M")}-{self.end_time.strftime("%H:%M")}',
                    self.get_status_display()]

    def get_start_datetime(self):
        return dt.strptime(f'{self.date.strftime("%Y %m %d")} {self.start_time.strftime("%H %M")}',
                           "%Y %m %d %H %M")

    def get_end_datetime(self):
        return dt.strptime(f'{self.date.strftime("%Y %m %d")} {self.end_time.strftime("%H %M")}',
                           "%Y %m %d %H %M")

    def get_date_time(self):
        return [int(x)
                for x in
                f'{self.date.strftime("%Y %m %d")} {self.start_time.strftime("%H %M")}'.split(" ")]

    def get_absolute_url(self):
        return reverse('eleccion:padron-detail', args=[str(self.id)])

    def __str__(self):
        return "{} - {}".format(self.date, self.title)


class Cargo(Base):
    name = models.CharField(max_length=100,
                            null=False, blank=False,
                            verbose_name='Nombre del Cargo',
                            unique=True)
    description = models.TextField(null=False, blank=False,
                                   verbose_name='Descripción')

    class Meta:
        verbose_name = "Cargo"
        verbose_name_plural = "Cargos"

    def get_field_values(self):
        return [self.name, self.description]

    def __str__(self):
        return "{}".format(self.name)


class Candidato(Base):
    postulation_date = models.DateField(auto_now_add=True)
    image = models.URLField(null=True, blank=True)
    # Relationships
    cargo = models.ForeignKey('Cargo',
                              on_delete=models.CASCADE, null=True)
    elector = models.ForeignKey(Elector,
                                on_delete=models.CASCADE, null=True)
    eleccion = models.ForeignKey('Eleccion',
                                 on_delete=models.CASCADE)

    class Meta:
        ordering = ['cargo', 'postulation_date']
        verbose_name = "Candidato"
        verbose_name_plural = "Candidatos"

    def get_absolute_url(self):
        return reverse('padron:edit-padron', args=[str(self.id)])

    def get_field_values(self):
        return [self.postulation_date,
                self.cargo,
                self.elector,
                self.eleccion]

    def __str__(self):
        return "{} - {}".format(self.elector.dni, self.cargo.name)


# _______________________________________________________
# PRE/POST SAVE
def set_slug_Eleccion(sender, instance, *args, **kwargs):
    if instance.id and instance.title and instance.date and not instance.slug:
        instance.slug = slugify(f'{instance.date}__{instance.id}_{instance.title}')
        instance.save()


post_save.connect(set_slug_Eleccion, sender=Eleccion)

apps/eleccion/views.py
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
#
from django.utils.decorators import method_decorator
#
from django.contrib.auth.decorators import login_required
# from django.contrib.auth.mixins import LoginRequiredMixin
#
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
# from django.views.generic.base import TemplateView
##
from django_q.models import Schedule
#
from .models import Padron, Cargo, Eleccion, Candidato
from .forms import (CargoForm,
                    EleccionForm,
                    CandidatoForm,
                    EleccionProgamadaForm)
from .utils import (set_active,
                    enable_form,
                    get_queryset_for_status,
                    get_queryset_by_state,
                    set_status
                    )
# from .decorators import group_required
# Create your views here.


# decorators = [login_required, group_required('administracion',)]
decorators = [login_required(login_url='usuarios:login'), ]


# ____________________________________________
# _Eleccion
@method_decorator(decorators, name='dispatch')
class EleccionListView(ListView):
    model = Eleccion
    template_name = "eleccion/eleccion_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Listado de Elecciones"
        context['page'] = "Listado de Elecciones"
        context['estado'] = self.request.GET.get('estado')
        context['elecciones_pasadas'] = get_queryset_for_status(self.model,
                                                                context['estado'],
                                                                [3, 4])
        context['elecciones_pendientes'] = get_queryset_for_status(self.model,
                                                                   context['estado'],
                                                                   [0, ])

        context['elecciones_programadas'] = get_queryset_for_status(self.model,
                                                                    context['estado'],
                                                                    [1, 2])
        #
        context['add_url'] = 'eleccion:add-eleccion'
        context['list_url'] = 'eleccion:eleccion-list'
        context['detail_url'] = 'eleccion:eleccion-detail'
        context['edit_url'] = 'eleccion:edit-eleccion'
        context['active_url'] = 'eleccion:active_eleccion'
        context['deactive_url'] = 'eleccion:deactive_eleccion'
        context['thead'] = ['Eleccion', 'Cargo',
                            'Fecha', 'Inicio-Cierre', 'Estado']
        return context


@method_decorator(decorators, name='dispatch')
class EleccionDetailView(DetailView):
    model = Eleccion
    template_name = "eleccion/eleccion_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Eleccion"
        return context


@method_decorator(decorators, name='dispatch')
class EleccionCreateView(CreateView):
    model = Eleccion
    form_class = EleccionForm
    template_name = "eleccion/create.html"
    success_url = reverse_lazy('eleccion:eleccion-list')

    def post(self, request, *args, **kwargs):
        form = EleccionForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(self.success_url)
        self.object = None
        context = self.get_context_data(**kwargs)
        context['form'] = form
        return render(request, self.template_name, context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_title'] = "Registrar una elección"
        context['add_new_message'] = []
        if not enable_form(Padron):
            context['void_select_field'] = True
            context['add_new_message'].append(("un PADRON registrado",
                                               reverse_lazy('padron:add-padron')))
        if not enable_form(Cargo):
            context['void_select_field'] = True
            context['add_new_message'].append(("un CARGO registrado",
                                               reverse_lazy('eleccion:add-cargo')))
        return context


@method_decorator(decorators, name='dispatch')
class EleccionUpdateView(UpdateView):
    model = Eleccion
    form_class = EleccionForm
    template_name = "eleccion/create.html"
    success_url = reverse_lazy('eleccion:eleccion-list')

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            self.object = form.save()
            return redirect('eleccion:eleccion-detail', slug=self.object.slug)
        else:
            self.object = None
        context = self.get_context_data(**kwargs)
        context['form'] = form
        return render(request, self.template_name, context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_title'] = "Editar datos de la elección"
        return context


@ login_required(login_url='usuarios:login')
def active_eleccion(request, pk):
    set_active(Eleccion.objects.get(pk=pk), True)
    return redirect('eleccion:eleccion-list')


@ login_required(login_url='usuarios:login')
def deactive_eleccion(request, pk):
    set_active(Eleccion.objects.get(pk=pk), False)
    return redirect('eleccion:eleccion-list')


@ method_decorator(decorators, name='dispatch')
class EleccionCandidatoCreateView(CreateView):
    model = Candidato
    form_class = CandidatoForm
    template_name = "eleccion/create.html"
    success_url = reverse_lazy('eleccion:eleccion-list')

    def get_initial(self):
        initial = super().get_initial()
        initial['eleccion'] = Eleccion.objects.get(slug=self.kwargs['slug']).pk
        return initial

    def post(self, request, *args, **kwargs):
        form = CandidatoForm(request.POST)
        print(form)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse_lazy('eleccion:eleccion-detail',
                                                     args=[kwargs['slug']]))
        self.object = None
        context = self.get_context_data(**kwargs)
        context['form'] = form
        return render(request, self.template_name, context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['id'] = self.request.GET.get('slug')
        context['form_title'] = "Registrar un candidato"
        return context


class EleccionProgramar(UpdateView):
    model = Eleccion
    form_class = EleccionProgamadaForm
    template_name = "eleccion/create.html"

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            obj = form.save()
            set_status(obj, 1)
            #
            Schedule.objects.create(name=f'{obj.id} st2: {obj.get_start_datetime()}',
                                         func='apps.eleccion.tasks.set_status',
                                         args=f'{obj.id},{2}',
                                         schedule_type='O',
                                         repeats=1,
                                         next_run=obj.get_start_datetime()
                                    )
            Schedule.objects.create(name=f'{obj.id} st3: {obj.get_end_datetime()}',
                                         func='apps.eleccion.tasks.set_status',
                                         args=f'{obj.id},{3}',
                                         schedule_type='O',
                                         repeats=1,
                                         next_run=obj.get_end_datetime()
                                    )
            #
            return redirect('eleccion:eleccion-detail', slug=obj.slug)
        self.object = None
        context = self.get_context_data(**kwargs)
        context['form'] = form
        return render(request, self.template_name, context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_title'] = "Horario de Inicio-Cierre"
        return context


# ____________________________________________
# _Cargo


@ method_decorator(decorators, name='dispatch')
class CargoListView(ListView):
    model = Cargo
    template_name = "eleccion/cargo_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Listado de Cargo"
        context['page'] = "Cargos"
        context['message_no_queryset'] = 'No hay cargos registrados'
        context['estado'] = self.request.GET.get('estado')
        context['object_list'] = get_queryset_by_state(self.model, context['estado'])
        context['add_url'] = 'eleccion:add-cargo'
        context['list_url'] = 'eleccion:cargo-list'
        # -- COMPLETAR
        context['detail_url'] = 'eleccion:edit-cargo'
        # ------------
        context['edit_url'] = 'eleccion:edit-cargo'
        context['active_url'] = 'eleccion:active_cargo'
        context['deactive_url'] = 'eleccion:deactive_cargo'
        context['thead'] = ['Cargo', 'Descripción']
        return context


@ login_required(login_url='usuarios:login')
def active_cargo(request, pk):
    set_active(Cargo.objects.get(pk=pk), True)
    return redirect('eleccion:cargo-list')


@ login_required(login_url='usuarios:login')

apps/eleccion/templates/eleccion/candidato_list.html
{% extends "index.html" %}
{% load static %}
{% block main %}
<div class="container-fluid">
  <h1 class="mt-4">{{page}}</h1>
  {% if object_list %}
  <div class="card">
    <div class="card-header d-flex justify-content-between bg-light">
      {% include "eleccion/snippets/new-act-deact.html"%}
    </div>
    <div class="card-body">
      <div class="table-responsive">
        {% include "eleccion/snippets/table.html" %}
      </div>
    </div>
  </div>
  {% else %}
  {% include "eleccion/snippets/no_objetc_list.html" %}
  {% endif %}
</div>
<!-- /container-fluid -->
{% endblock %}

{% block script_dataTable %}
<script type="text/javascript">
  $(document).ready(function() {
    $('#data1').DataTable();
  });
</script>
{% endblock %}

apps/eleccion/templates/eleccion/cargo_list.html
{% extends "index.html" %}
{% load static %}
{% block main %}
<div class="container-fluid">
  <h1 class="mt-4">{{page}}</h1>
  {% if object_list %}
  <div class="card">
    <div class="card-header d-flex justify-content-between bg-light">
      {% include "eleccion/snippets/new-act-deact.html"%}
    </div>
    <div class="card-body">
      <div class="table-responsive">
        {% include "eleccion/snippets/table.html" %}
      </div>
    </div>
  </div>
  {% else %}
  {% include "eleccion/snippets/no_objetc_list.html" %}
  {% endif %}
</div>
<!-- /container-fluid -->
{% endblock %}

{% block script_dataTable %}
<script type="text/javascript">
  $(document).ready(function() {
    $('#data1').DataTable();
  });
</script>
{% endblock %}

apps/eleccion/templates/eleccion/create.html
{% extends 'base.html' %}

{% block main %}
<div class="row bg-secondary">
    <div class="col-sm-4"></div>
    <div class="col-sm-4">
      <!--SI NECESITA DE OTRA/S RELACIONES-->
      {% if void_select_field %}
        <div class="card">
          <div class="card-header">
            <h4 class="card-title">Necesita al menos..</h4>
          </div>
          <div class="card-body">
            {% for message in add_new_message %}
            <h5 class="card-title">{{ message.0 }}</h5>
            <a class="btn btn-block btn-primary mt-1" href={{message.1}}>Registrar Ahora</a>
            {% endfor %}
          </div>
          <div class="card-footer text-center">
            * * *
          </div>
        </div>


      <!--/SI NECESITA DE OTRA/S RELACIONES-->
      {% else %}
      <div class="card">
        <form method="post">
          {% csrf_token %}
          <div class="card-header text-center"><h5>{{form_title}}</h5></div>
          <div class="card-body">
            {% for field in form.visible_fields %}
              <label class="font-weight-bold">{{field.label}}</label>
              <div class="form-group">
                {% if field.field.widget.input_type == "select" %}
                  <div class="row">
                    <div class="col-sm-8">{{field}}</div>
                    <div class="col-sm-2"><a class="btn btn-primary" href="#">Nuevo</a></div>
                  </div>
                {% else %}
                  {{field}}
                {% endif %}
              </div>
            {% endfor %}
          </div>
          <div class="card-footer">
            <button class="btn-block btn-lg btn-primary">Registrar</button>
          </div>
        </form>
      </div>
      {% endif %}
    </div>
    <div class="col-sm-4">{{form.errors}}</div>
</div>
{% endblock %}

apps/eleccion/templates/eleccion/eleccion_detail.html
{% extends 'index.html' %}
{% load static %}

{% block main %}
<div class="container-fluid">
  <ol class="breadcrumb mt-2">
    {% block breadcrumb %}
    <li class="breadcrumb-item active">
      <a href={% url 'eleccion:eleccion-list' %}>Elecciones</a></li>
    <li class="breadcrumb-item">{{object}}</li>
    {% endblock %}
  </ol>
  <div class="card mb-4">
    <div class="card-header">
      {{object.title}}
    </div>
    <!-- card-body -->
    <div class="card-body">
      <div class="row">
        <div class="col">
          <ul class="list-group list-group-flush">
            <li class="list-group-item"><b>Fecha:</b> {{object.date}}</li>
            <li class="list-group-item"><b>Inicio-Cierre:</b>
              {% if object.status %}{{object.start_time}}hs-{{object.end_time}}hs {% else %}00:00hs-00:00hs{% endif %}</li>
            <li class="list-group-item"><b>Estado:</b> {{object.get_status_display}}</li>
            <li class="list-group-item"><b>Cargo:</b> {{object.cargo}}</li>
            <li class="list-group-item"><b>Padron:</b>
              <a href="{{object.padron.get_absolute_url}}" target="_blank">{{object.padron}}
              </a>
            </li>
          </ul>
        </div>
        <div class="col">
          <h5>Candidatos: {{object.candidato_set.all.count}}</h5>
          {% for obj in object.candidato_set.all %}
          <ul class="list-group list-group-flush">
            <li class="list-group-item"> <a href="{{obj.get_absolute_url}}">{{obj}}</a> </li>
          </ul>
          {% endfor %}
        </div>
      </div>
    </div>
    <!-- /card-body -->

    <div class="card-footer">
      <div class="container-fluid d-flex content-justify-between">
        <div class="col">
          <a class="btn btn-warning" href={% url 'eleccion:edit-eleccion' object.slug %}>Editar</a>
          <a class="btn btn-secondary" href="{{object.padron.get_absolute_url}}">Ver Padron</a>
          <a class="btn btn-primary" href={% url 'eleccion:eleccion-candidato' object.slug %}>Postular Candidato</a>
          <!--# path('addreview/<int:book_pk>/', AddReview.as_view(), name = 'add-review')-->
        </div>
        <a class="btn btn-success" href={% url 'eleccion:programar-eleccion' object.slug %}>Programar</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

apps/eleccion/templates/eleccion/eleccion_list.html
{% extends "index.html" %}
{% load static %}
{% block main %}
<!-- Card with card-header-tabs -->
<div class="container">
  <div class="card-fluid">
    <!-- Card-header -->
    <div class="card-header">
      <ul class="nav nav-tabs card-header-tabs" id="eleccion-list" role="tablist">
        <!-- /Pasadas-Pendientes-Programadas -->
        <li class="nav-item">
          <a class="nav-link active" href="#pasadas" role="tab" aria-controls="pasadas" aria-selected="true">
            Pasadas
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#pendientes" role="tab" aria-controls="pendientes" aria-selected="false">
            Pendientes
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#programadas" role="tab" aria-controls="programadas" aria-selected="false">
            Programadas
          </a>
        </li>
        <!-- /Pasadas-Pendientes-Programadas -->
      </ul>
    </div>
    <!-- /Card-header -->
    <!-- Card-bodys -->
    <div class="card-body">
      <!--h4 class="card-title">TITULO</h4>
      <h6 class="card-subtitle mb-2">Subtitulo</h6-->
      <!-- tab-content pasadas-pendientes-programadas -->
      <div class="tab-content mt-3">
        <!-- tab-pane pasadas -->
        <div class="tab-pane active" id="pasadas" role="tabpanel">
          <h6 class="card-subtitle mb-2">Tabla de elecciones pasadas</h6>
          {% if elecciones_pasadas %}
          <div class="table-responsive">
            {% include "eleccion/snippets/table_elecciones.html" with id_table="data1" object_list=elecciones_pasadas hidden="d-none"%}
          </div>
          {% else %}
          {% include "eleccion/snippets/no_objetc_list_eleccion.html" with status="pasadas" hidden="d-none"%}
          {% endif %}
        </div>
        <!-- ./tab-pane pasadas -->
        <!-- tab-pane pendientes -->
        <div class="tab-pane" id="pendientes" role="tabpanel" aria-labelledby="history-tab">
          <h6 class="card-subtitle mb-2">Tablas elecciones pendientes</h6>
          {% if elecciones_pendientes %}
          <div class="table-responsive">
            {% include "eleccion/snippets/table_elecciones.html" with id_table="data2" object_list=elecciones_pendientes hidden=""%}
          </div>
          {% else %}
          {% include "eleccion/snippets/no_objetc_list_eleccion.html" with status="pendientes" %}
          {% endif %}
        </div>
        <!-- ./tab-pane pendientes -->
        <!-- tab-pane programadas -->
        <div class="tab-pane" id="programadas" role="tabpanel" aria-labelledby="deals-tab">
          <h6 class="card-subtitle mb-2">Tablas elecciones programadas</h6>
          {% if elecciones_programadas %}
          {% include "eleccion/snippets/table_elecciones.html" with id_table="data3" object_list=elecciones_programadas hidden=""%}
          {% else %}
          {% include "eleccion/snippets/no_objetc_list_eleccion.html" with status="programadas" %}
          {% endif %}
        </div>
        <!-- ./tab-pane programadas -->
      </div>
      <!-- ./tab-content pasadas-pendientes-programadas -->
    </div>
    <!-- /Card-bodys -->
  </div>
</div>
<!-- /Card with card-header-tabs -->
{% endblock %}

{% block script_dataTable %}
<script type="text/javascript">
  // Call the dataTables jQuery plugin
  $(document).ready(function() {
    var tabla1 = iniciarDataTable('data1');
    var tabla2 = iniciarDataTable('data2');
    var tabla3 = iniciarDataTable('data3');
    $("#eleccion-list a").on("click", function(e) {
      e.preventDefault();
      $(this).tab("show");
      var referencia = $(event.target).attr("href");
      if (referencia == "#pasadas")
        tabla1.columns.adjust();
      if (referencia == "#pendientes")
        tabla2.columns.adjust();
      if (referencia == "#programadas")
        tabla3.columns.adjust();
    });
  });
  // https://es.stackoverflow.com/questions/144360/datatables-en-tabs-dinamicas-se-inicializan-mal
  function iniciarDataTable(id) {
    var table = $('#' + id).DataTable({
      "scrollY": "400px",
      "scrollCollapse": true,
      "paging": false,
      scrollX: true,
    });
    return table;
  };
</script>
{% endblock %}