apps/eleccion/urls.py
"""conf URL Configuration
The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
"""
from django.urls import path
from . import views

app_name = 'eleccion'
urlpatterns = [
    # _Cargo
    path('cargos/', views.CargoListView.as_view(), name='cargo-list'),
    path('cargos/active/<int:pk>', views.active_cargo, name='active_cargo'),
    path('cargos/deactive/<int:pk>', views.deactive_cargo, name='deactive_cargo'),
    path('cargos/add/', views.CargoCreateView.as_view(), name='add-cargo'),
    path('cargos/edit/<int:pk>/', views.CargoUpdateView.as_view(), name='edit-cargo'),
    # _Candidato
    path('candidatos/', views.CandidatoListView.as_view(), name='candidato-list'),
    path('candidatos/active/<int:pk>', views.active_candidato, name='active_candidato'),
    path('candidatos/deactive/<int:pk>',
         views.deactive_candidato, name='deactive_candidato'),
    path('candidatos/add/', views.CandidatoCreateView.as_view(), name='add-candidato'),
    path('candidatos/edit/<int:pk>/',
         views.CandidatoUpdateView.as_view(), name='edit-candidato'),
    # _ Eleccion
    path('', views.EleccionListView.as_view(), name='eleccion-list'),
    path('active/<int:pk>', views.active_eleccion, name='active_eleccion'),
    path('deactive/<int:pk>', views.deactive_eleccion, name='deactive_eleccion'),
    path('add/', views.EleccionCreateView.as_view(), name='add-eleccion'),
    # path('edit/<int:pk>/', views.EleccionUpdateView.as_view(), name='edit-eleccion'),
    path('edit/<slug:slug>/', views.EleccionUpdateView.as_view(), name='edit-eleccion'),
    path('<slug:slug>/', views.EleccionDetailView.as_view(), name='eleccion-detail'),
    path('<slug:slug>/add-candidato',
         views.EleccionCandidatoCreateView.as_view(), name='eleccion-candidato'),
    path('<slug:slug>/programar/',
         views.EleccionProgramar.as_view(), name='programar-eleccion'),

]

apps/index/urls.py
"""conf URL Configuration
The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
"""
from django.urls import path
from .views import Index, Sumary

app_name = 'index'
urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('resumen/', Sumary.as_view(), name='sumary'),
]

apps/padron/urls.py
"""conf URL Configuration
The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
"""
from django.urls import path
from . import views

app_name = 'padron'
urlpatterns = [
    # Padron
    path('', views.PadronListView.as_view(), name='padron-list'),
    path('<int:pk>/', views.PadronDetailView.as_view(), name='padron-detail'),
    path('active/<int:pk>', views.active_padron, name='active_padron'),
    path('deactive/<int:pk>', views.deactive_padron, name='deactive_padron'),
    path('add/', views.PadronCreateView.as_view(), name='add-padron'),
    path('edit/<int:pk>/', views.PadronUpdateView.as_view(), name='edit-padron'),
    # Elector
    path('electores', views.ElectorListView.as_view(), name='elector-list'),
    path('electores/active/<int:pk>', views.active_elector, name='active_elector'),
    path('electores/deactive/<int:pk>', views.deactive_elector, name='deactive_elector'),
]

apps/usuarios/urls.py
"""conf URL Configuration
The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
"""
from django.urls import path
from .views import logout_view, LoginFormView  # , UserCreateView

app_name = 'usuarios'
urlpatterns = [
    path('login/', LoginFormView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    # path('create_user/', UserCreateView.as_view(), name='create-user'),
]

conf/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.index.urls')),
    path('accounts/', include('apps.usuarios.urls')),
    path('padron/', include('apps.padron.urls')),
    path('eleccion/', include('apps.eleccion.urls')),
    path('votacion/', include('apps.votacion.urls')),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
  <title>{{title}}</title>
  {% include "head.html" %}
</head>

<body class="sb-nav-fixed">
  {% include "navbar.html" %}
  <div id="layoutSidenav">
    <div id="layoutSidenav_nav">
      {% include "sidenavAccordion.html" %}
    </div>
    <div id="layoutSidenav_content">
      <main>
        {% block main %}
        {% endblock %}
      </main>

      {% include "footer.html" %}
    </div>
  </div>

  {% include "scripts.html" %}
  {% block script_dataTable %}
  {% endblock %}
</body>

</html>

templates/footer.html
<footer class="py-4 bg-light mt-auto">
  <div class="container-fluid">
    <div class="d-flex align-items-center justify-content-between small">
      <div class="text-muted">Copyright &copy; Your Website 2020</div>
      <div>
        <a href="#">Privacy Policy</a>
        &middot;
        <a href="#">Terms &amp; Conditions</a>
      </div>
    </div>
  </div>
</footer>
<!-- /footer -->

templates/head.html
{% load static %}

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <link href="{% static 'lib/css/styles.css' %}" rel="stylesheet">
  <!--DataTables-->
  <link href="{% static 'lib/DataTables/datatables.min.css' %}" rel="stylesheet">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js" crossorigin="anonymous"></script>


{% block head %}
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block title %}{{title}}{% endblock %}
{% block main %}
<div class="container-fluid">
  <h1 class="mt-4">Bienvenido {{user}}</h1>

  <ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Elecciones</li>
  </ol>
  <!--Proximas elecciones-->
  {% if upcoming_elecciones %}
  <div class="row">
    <h3 class="mt-4">Proximas elecciones:</h3>
  </div>
  <div class="row-fluid">
    <div class="list-group">
    {% for upcoming in upcoming_elecciones %}
      <li class="list-group-item d-flex justify-content-between">
        <a href={% url 'votacion:votacion' upcoming.slug %}><b>{{upcoming}}</b></a>
        <a class="btn btn-primary" href={% url 'votacion:votacion' upcoming.slug %}>Ver Candidatos</a>
      </li>
    {% endfor %}
    </div>

  </div>
  {% endif %}
  <!-- ./Proximas elecciones-->
  <!--Elecciones en curso-->
  {% if current_elecciones %}
  <div class="row">
    <h3 class="h3 mt-4">Elecciones en Curso:</h3>
  </div>
  <div class="row-fluid">
    <div class="list-group">
      {% for current in current_elecciones %}
        <li class="list-group-item d-flex justify-content-between">
        <a href={% url 'votacion:votacion' current.slug %}><b>{{current}}</b></a>
        <a class="btn btn-primary" href={% url 'votacion:votacion' current.slug %}>Votar</a>
      </li>
      {% endfor %}
    </div>
  </div>
  {% endif %}
  <!-- ./Elecciones en curso-->
</div>
<!-- /container-fluid -->
{% endblock %}
{% block script_dataTable %}
<script type="text/javascript">
  // Call the dataTables jQuery plugin
  $(document).ready(function() {
    var tabla1 = iniciarDataTable('data1');
    var tabla2 = iniciarDataTable('data2');
    var tabla3 = iniciarDataTable('data3');
    $("#eleccion-list a").on("click", function(e) {
      e.preventDefault();
      $(this).tab("show");
      var referencia = $(event.target).attr("href");
      if (referencia == "#pasadas")
        tabla1.columns.adjust();
      if (referencia == "#pendientes")
        tabla2.columns.adjust();
      if (referencia == "#programadas")
        tabla3.columns.adjust();
    });
  });
  // https://es.stackoverflow.com/questions/144360/datatables-en-tabs-dinamicas-se-inicializan-mal
  function iniciarDataTable(id) {
    var table = $('#' + id).DataTable({
      "scrollY": "400px",
      "scrollCollapse": true,
      "paging": false,
      scrollX: true,
    });
    return table;
  };
</script>
{% endblock %}

templates/index0.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
      <div class="col-sm-2">

      </div>
      <div class="col-sm-4 border border-primary rounded bg-light">
        <h2><u>Resumen</u>:</h2>
        <ul class="list-group">
        {% for entry, value in sumary.items %}
          <li class="list-group-item d-flex justify-content-between align-items-center mb-1">
            {{entry}}:
            {% if value %}
             <span class="badge badge-primary badge-pill">
               <a href="#"><h3>{{value}}</h3> </a>
             </span>
            {% else %}
              <span>No hay registros, <a href="#">Registrar Ahora</a></span>
            {% endif %}
          </li>
        {% endfor %}
        </ul>
      </div>
      <div class="col">

      </div>
    </div>
{% endblock %}

templates/list_base.html
{% extends "base.html" %}
{% load static %}

{% comment %} content {% endcomment %}
{% block main %}
<div class="container-fluid">
  <!--h1 class="mt-4">{{entity}}</h1-->
  <ol class="breadcrumb mt-4">
    {% block breadcrumb %}
    {% endblock %}
  </ol>
  {% if object_list  %}
  <div class="card">
    <div class="card-header d-flex justify-content-between bg-light">
      {% include "core/snippets/new-act-deact.html"%}
    </div>
    <div class="card-body">
      <div class="table-responsive">
        {% block object_list %}{% endblock %}
      </div>
    </div>
  </div>
  {% else %}
    {% block no_object_list %}
    {% include "core/snippets/no_objetc_list.html" %}
    {% endblock %}
  {% endif %}

</div>
{% endblock %}

templates/navbar.html
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href={% url 'index:index' %}> EleccVi</a>
    <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
  </div>
  <!-- Navbar-->
  <div class="container justify-content-end">
    <ul class="navbar-nav ml-auto ml-md-0">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
          <a class="dropdown-item" href="#">Settings</a>
          <a class="dropdown-item" href="#">Activity Log</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href={% url 'usuarios:logout' %}>Logout</a>
        </div>
      </li>
    </ul>
  </div>
</nav>
<!-- /navbar -->

templates/navbar0.html
<!-- A grey horizontal navbar that becomes vertical on small screens -->
<nav class="navbar navbar-expand-sm bg-pink">
  <!-- Links -->
  <ul class="navbar-nav">
  {% if user.is_authenticated %}
    <li class="nav-item">
      <a class="nav-link btn btn-outline-info mr-1" href={% url 'core:eleccion-list' %}>Elecciones</a>
    <li class="nav-item">
      <a class="nav-link btn btn-outline-info mr-1" href="#">Candidatos</a>
    <li class="nav-item">
      <a class="nav-link btn btn-outline-info mr-1" href={% url 'core:cargo-list' %}>Cargos</a>
    </li>
    <li class="nav-item">
      <a class="nav-link btn btn-outline-info mr-1" href={% url 'core:padron-list' %}>Padrones</a>
    </li>
    <li class="nav-item">
      <a class="nav-link btn btn-outline-info mr-1" href={% url 'core:elector-list' %}>Electores</a>
    </li>
  </ul>
  <ul class="nav navbar-nav ml-auto">
    <li class="navbar-item">
      <a class="nav-link btn btn-outline-danger" href={% url 'logout' %}>Logout</a>
    </li>
  </ul>

{% endif %}
</nav>

templates/scripts.html
{% load static %}
<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
<script src="{% static 'lib/js/scripts.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
<script src="{% static 'lib/assets/demo/chart-area-demo.js' %}"></script>
<script src="{% static 'lib/assets/demo/chart-bar-demo.js' %}"></script>
<!--script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script-->
<!--script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script-->
<!--script src="{% static 'lib/assets/demo/datatables-demo.js' %}"></script-->
<!--Datatable-->
<script src="{% static 'lib/DataTables/datatables.min.js' %}"></script>

templates/sidenavAccordion.html
<nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
  <div class="sb-sidenav-menu">

    <div class="nav">
      <div class="sb-sidenav-menu-heading">ADMIN</div>
      <a class="nav-link" href={% url 'admin:index' %}>
        Admin Site
      </a>
      <div class="sb-sidenav-menu-heading">DATA</div>
      <a class="nav-link" href={% url 'index:index' %}>
        <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
        Resumen
      </a>
      <!-- nav-link collapsed Gestión de Padrón -->
      <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#Padron" aria-expanded="false" aria-controls="Padron">
        <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
        Gestión de Padrón
        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
      </a>
      <div class="collapse" id="Padron" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
        <nav class="sb-sidenav-menu-nested nav">
          <a class="nav-link" href={% url 'padron:padron-list' %}>Padrones</a>
          <a class="nav-link" href={% url 'padron:elector-list' %}>Electores</a>
        </nav>
      </div>
      <!-- /nav-link collapsed Gestión de Padrón -->

      <!-- nav-link collapsed Gestión de Elección -->
      <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#Eleccion" aria-expanded="false" aria-controls="collapsePages">
        <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
        Gestión de Elección
        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
      </a>
      <div class="collapse" id="Eleccion" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
        <nav class="sb-sidenav-menu-nested nav">
          <a class="nav-link" href={% url 'eleccion:cargo-list' %}>Cargos</a>
          <a class="nav-link" href={% url 'eleccion:candidato-list' %}>Candidatos</a>
          <a class="nav-link" href={% url 'eleccion:eleccion-list' %}>Elecciones</a>
        </nav>
      </div>
      <!-- ./nav-link collapsed Gestión de Elección -->
      <div class="sb-sidenav-menu-heading">Conteos</div>
      <a class="nav-link" href="charts.html">
        <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
        Charts
      </a>
      <a class="nav-link" href="tables.html">
        <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
        Tables
      </a>
    </div>
  </div>
  <div class="sb-sidenav-footer">
    <div class="small">Loggeado como:</div>
    {{user}}
  </div>
</nav>

templates/sumary.html
{% extends 'base.html' %}
{% block title %}{{title}}{% endblock %}
{% block main %}
<div class="container-fluid">
  <h1 class="mt-4">Resumen</h1>

  <ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Resumen</li>
  </ol>

  <div class="row">
    {% for entry, value in sumary.items %}
    <div class="col-xl-6 col-md-12">
      {% if value.0 %}
      <div class="card bg-primary text-white mb-4">
        <div class="card-header text-center"><b>{{entry}}</b></div>
        <div class="card-body bg-primary">
          <ul>
            <li>Total: {{value.0}}</li>
            <li>Activos: {{value.1}}</li>
            <li>Inactivos: {{value.2}}</li>
          </ul>
        </div>
        <div class="card-footer d-flex justify-content-between">
          <a class="small text-white" href={% url value.3 %}>
            <b>Listado</b>
          </a>
          <a class="small text-white" href={% url value.4 %}>
            <b>Registrar</b>
          </a>
        </div>
      </div>
      {% else %}
      <div class="card bg-warning text-white mb-4">
        <div class="card-header text-center"><b>{{entry}}</b></div>
        <div class="card-body">
          <h4>No hay registros de {{entry}}</h4><br>
        </div>
        <div class="card-footer d-flex justify-content-center">
          <a class="small text-white" href={% url value.1 %}>
            <b>Registrar Ahora</b>
          </a>
        </div>
      </div>
      {% endif %}
    </div>
    {% endfor %}


  </div>
</div>
<!-- /container-fluid -->
{% endblock %}